# Generated by Django 3.2.2 on 2021-05-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_just_recorder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NextCounter',
        ),
    ]
